/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

//#include "../JuceLibraryCode/JuceHeader.h"	// Not necessary to include this here
												// It's included indirectly by the other header(s) below
												// If this is included here, it causes an error in Windows builds
												// #error :  gl.h included before glew.h
#include "MainComponent.h"
#include "MotionServer.h"

//==============================================================================
class AirHarpApplication  : public JUCEApplication
                          //, public AudioIODeviceCallback
{
public:
    //==============================================================================
    AirHarpApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return true; }

    //==============================================================================
    void initialise (const String& /*commandLine*/)
    {
        // This method is where you should put your application's initialisation code..

        mainWindow = new MainWindow();
        audioDeviceManager.initialise (2, 2, 0, true, String::empty, 0);
        //audioDeviceManager.addAudioCallback(this);
        audioSourcePlayer.setSource (&Drums::instance());
        audioDeviceManager.addAudioCallback (&audioSourcePlayer);
        Logger::outputDebugString(audioDeviceManager.getCurrentAudioDevice()->getName());
    }

    void shutdown()
    {
        // Add your application's shutdown code here..

        audioDeviceManager.removeAudioCallback (&audioSourcePlayer);
		MotionDispatcher::destruct();

        mainWindow = nullptr; // (deletes our window)
        //audioDeviceManager.removeAudioCallback(this);
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void audioDeviceAboutToStart (AudioIODevice* /*device*/)
    {
        
    }
    void audioDeviceStopped()
    {
        
    }
    void audioDeviceIOCallback (const float** /*inputChannelData*/, int /*numInputChannels*/,
                                float** /*outputChannelData*/, int /*numOutputChannels*/, int /*numSamples*/)
    {
    }
    
    void anotherInstanceStarted (const String& /*commandLine*/)
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

    //==============================================================================
    /*
        This class implements the desktop window that contains an instance of
        our MainContentComponent class.
    */
    class MainWindow    : public DocumentWindow
    {
    public:
        MainWindow()  : DocumentWindow ("MainWindow",
                                        Colours::lightgrey,
                                        DocumentWindow::allButtons)
        {
            setContentOwned (new MainContentComponent(), true);

            centreWithSize (getWidth(), getHeight());
            setVisible (true);
            setUsingNativeTitleBar(true);
            setResizable(true, false);
        }

        void closeButtonPressed()
        {
            // This is called when the user tries to close this window. Here, we'll just
            // ask the app to quit when this happens, but you can change this to do
            // whatever you need.
            JUCEApplication::getInstance()->systemRequestedQuit();
        }

        /* Note: Be careful if you override any DocumentWindow methods - the base
           class uses a lot of them, so by overriding you might break its functionality.
           It's best to do all your work in your content component instead, but if
           you really have to override any DocumentWindow methods, make sure your
           subclass also calls the superclass's method.
        */

    private:
        JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainWindow)
    };

private:
    ScopedPointer<MainWindow> mainWindow;
    AudioDeviceManager audioDeviceManager;
    AudioSourcePlayer audioSourcePlayer;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (AirHarpApplication)
